### ISSUE TITLE
Ignore DTDs

### ISSUE THREAD

**Issue by superdude264** [kermitt2/Pub2TEI#3]
In trying to get Pub2TEI working on the grobid gold standard data from PMC, I ran into the DTD issues mentioned in the README.  After some research, I was able to discover that DTD loading can be disabled with the following switch:

```shell
--parserFeature?uri=http%3A//apache.org/xml/features/nonvalidating/load-external-dtd:false
```

**References:**
* [Saxon docs on the `--feature` switch](https://www.saxonica.com/documentation/index.html#!using-xsl/commandline)
* [StackOverflow response from Saxon developer Michael Kay](https://stackoverflow.com/questions/29410065/)
* [Xerces Documentation on `load-external-dtd`](http://xerces.apache.org/xerces2-j/features.html#nonvalidating.load-external-dtd)

I've attached a file from the grobid PMC gold standard data I was having trouble with.  The new switch allows the conversion to proceed.

[sample.zip](https://github.com/kermitt2/Pub2TEI/files/5888544/sample.zip)

---

The sample command in the README could be updated to:
```shell
java -jar Samples/saxon9he.jar \
	--parserFeature?uri=http%3A//apache.org/xml/features/nonvalidating/load-external-dtd:false \
	-a:off \
	-dtd:off \
	-expand:off \
	-o:out.tei.xml \
	-s:Samples/TestPubInput/BMJ/bmj_sample.xml \
	-t \
	-xsl:Stylesheets/Publishers.xsl
```

**Comment by kermitt2** [comment]
Thanks you very much @superdude264 for the info! And sorry for answering only now (I overlooked your issue, and although I am using Pub2TEI quite frequently, it does not require a lot of updates).

This is very useful, I've updated the readme.

**Comment by superdude264** [comment]
No problem, and thank you for the shout out. Docs look good to me.
